export const APPS = [
  // Productivity
  { id: 'excalidraw',   icon:'🎨', name:'Excalidraw',      desc:'Virtual whiteboard for sketching hand-drawn diagrams. Open source, works offline.', category:'Productivity',    price:'Free', url:'https://excalidraw.com', score:3,  trust:'green',  installs:'2.1M', rankingScore:96, safetyScore:99, averageRating:4.9, totalReviews:4200, publishedAt:'2024-01-15', developerTrust:98, installVelocity:95, badges:['trending','verified','top_rated'],
    developer:'Excalidraw Team', size:'1.8 MB',
    longDesc:'Excalidraw is a free, open-source virtual whiteboard for sketching hand-drawn-like diagrams. It works entirely offline in your browser with no account required. Collaborate in real time via shareable links, export to PNG or SVG, and use the extensive shape library for flowcharts, wireframes, and architecture diagrams.',
    whatsNew:'Added dark mode toggle, improved shape snapping, new arrow styles, and reduced bundle size by 18%.',
    permissions:['None — fully offline'],
    screenshots:[
      { title:'Canvas', caption:'Infinite whiteboard with hand-drawn style shapes', color:'#6c5ce7', mockup:'editor', link:'https://excalidraw.com' },
      { title:'Shapes & Tools', caption:'Rectangles, arrows, text, and freehand drawing', color:'#a29bfe', mockup:'grid', link:'https://excalidraw.com' },
      { title:'Collaboration', caption:'Real-time multiplayer editing with shared links', color:'#74b9ff', mockup:'editor', link:'https://excalidraw.com/#room' },
      { title:'Export Options', caption:'Export to PNG, SVG, or share via live link', color:'#55efc4', mockup:'list', link:'https://excalidraw.com' },
    ] },
  { id: 'todoist',      icon:'✅', name:'Todoist',          desc:'Powerful task manager with projects, labels, filters, and natural language input.',  category:'Productivity',    price:'Free', url:'https://todoist.com', score:5,  trust:'green',  installs:'1.8M', rankingScore:93, safetyScore:97, averageRating:4.8, totalReviews:3800, publishedAt:'2024-03-10', developerTrust:96, installVelocity:90, badges:['trending','verified','top_rated'],
    developer:'Doist', size:'3.2 MB',
    longDesc:'Todoist is a powerful task manager used by over 30 million people. Organize your work and life with projects, sections, labels, and priority levels. Use natural language input to quickly add tasks like "Meeting with Sarah tomorrow at 3pm" and let Todoist parse the details automatically.',
    whatsNew:'New board view for projects, improved natural language parsing, collaborative task comments, and notification improvements.',
    permissions:['Internet access', 'Notifications'],
    screenshots:[
      { title:'Task Inbox', caption:'Quick-add tasks with natural language dates', color:'#e17055', mockup:'list', link:'https://todoist.com/app/inbox' },
      { title:'Projects', caption:'Organize tasks into projects with sections', color:'#d63031', mockup:'list', link:'https://todoist.com/app/projects' },
      { title:'Filters & Labels', caption:'Custom filters to find tasks instantly', color:'#e84393', mockup:'grid', link:'https://todoist.com/app/filters-labels' },
      { title:'Upcoming View', caption:'See all tasks across projects by date', color:'#fd79a8', mockup:'list', link:'https://todoist.com/app/upcoming' },
    ] },
  { id: 'notion',       icon:'📝', name:'Notion',           desc:'All-in-one workspace for notes, docs, wikis, and project management.',              category:'Productivity',    price:'Free', url:'https://www.notion.so', score:4,  trust:'green',  installs:'3.5M', rankingScore:97, safetyScore:98, averageRating:4.8, totalReviews:5100, publishedAt:'2024-02-20', developerTrust:97, installVelocity:93, badges:['trending','verified','top_rated'],
    developer:'Notion Labs', size:'4.1 MB',
    longDesc:'Notion is an all-in-one workspace that combines notes, docs, wikis, databases, and project management into a single tool. Build custom workflows with linked databases, create team wikis, and use 1000+ community templates. AI-powered writing assistance helps you draft, summarize, and brainstorm.',
    whatsNew:'Notion AI assistant improvements, new calendar database view, improved mobile editor, and faster page load times.',
    permissions:['Internet access', 'Clipboard'],
    screenshots:[
      { title:'Workspace', caption:'Pages, databases, and wikis in one place', color:'#2d3436', mockup:'cards', link:'https://www.notion.so' },
      { title:'Databases', caption:'Tables, boards, calendars, and gallery views', color:'#636e72', mockup:'grid', link:'https://www.notion.so/product/databases' },
      { title:'Templates', caption:'Start from 1000+ community templates', color:'#b2bec3', mockup:'cards', link:'https://www.notion.so/templates' },
      { title:'AI Assistant', caption:'Write, summarize, and brainstorm with AI', color:'#74b9ff', mockup:'chat', link:'https://www.notion.so/product/ai' },
    ] },

  // Finance
  { id: 'mint-alt',     icon:'💰', name:'Actual Budget',    desc:'Privacy-first budgeting app. Local-first, open source, sync across devices.',       category:'Finance',         price:'Free', url:'https://actualbudget.org', score:6,  trust:'green',  installs:'180k', rankingScore:82, safetyScore:95, averageRating:4.6, totalReviews:920,  publishedAt:'2024-05-12', developerTrust:88, installVelocity:72, badges:['verified','top_rated'],
    developer:'Actual Budget', size:'2.4 MB',
    longDesc:'Actual Budget is a privacy-first, local-first budgeting app that gives you full control over your financial data. Uses envelope-style budgeting to allocate every dollar. Open source and self-hostable with optional end-to-end encrypted sync across devices.',
    whatsNew:'New spending reports with category breakdowns, improved import from bank CSV files, and dark mode support.',
    permissions:['None — local storage only'],
    screenshots:[
      { title:'Budget Overview', caption:'Envelope-style budgeting with monthly totals', color:'#00b894', mockup:'chart', link:'https://actualbudget.org' },
      { title:'Transactions', caption:'Import bank transactions or add manually', color:'#00cec9', mockup:'list', link:'https://actualbudget.org' },
      { title:'Reports', caption:'Spending charts and cash flow analysis', color:'#0984e3', mockup:'chart', link:'https://actualbudget.org' },
      { title:'Accounts', caption:'Track checking, savings, and credit cards', color:'#6c5ce7', mockup:'list', link:'https://actualbudget.org' },
    ] },
  { id: 'wise',         icon:'💸', name:'Wise',             desc:'Send money internationally with real exchange rates and low fees.',                 category:'Finance',         price:'Free', url:'https://wise.com', score:8,  trust:'green',  installs:'950k', rankingScore:88, safetyScore:94, averageRating:4.7, totalReviews:2800, publishedAt:'2024-04-08', developerTrust:94, installVelocity:82, badges:['trending','verified'],
    developer:'Wise (TransferWise)', size:'3.8 MB',
    longDesc:'Wise lets you send money internationally using the real mid-market exchange rate with transparent, low fees. Hold and convert 50+ currencies, get local bank details in 10 currencies, and spend abroad with the Wise debit card. Trusted by over 16 million customers worldwide.',
    whatsNew:'Added real-time rate alerts, improved multi-currency account dashboard, and faster transfer tracking.',
    permissions:['Internet access'],
    screenshots:[
      { title:'Send Money', caption:'Transfer to 80+ countries with real rates', color:'#00b894', mockup:'form', link:'https://wise.com/send' },
      { title:'Multi-Currency', caption:'Hold and convert 50+ currencies instantly', color:'#a3cb38', mockup:'grid', link:'https://wise.com/multi-currency-account' },
      { title:'Rate Alerts', caption:'Get notified when exchange rates hit your target', color:'#ffeaa7', mockup:'chart', link:'https://wise.com/rate-alerts' },
      { title:'Activity', caption:'Track all transfers with real-time status', color:'#74b9ff', mockup:'feed', link:'https://wise.com' },
    ] },

  // Health
  { id: 'wger',         icon:'🏃', name:'wger Fitness',     desc:'Open source fitness tracker. Log workouts, manage routines, track nutrition.',      category:'Health',          price:'Free', url:'https://wger.de', score:5,  trust:'green',  installs:'120k', rankingScore:72, safetyScore:93, averageRating:4.4, totalReviews:560,  publishedAt:'2024-06-20', developerTrust:82, installVelocity:58, badges:['verified'],
    developer:'wger Project', size:'1.9 MB',
    longDesc:'wger is a free, open source web application for managing workouts, nutrition, and body measurements. Log exercises with sets, reps, and weight. Create weekly routines and track your caloric intake. All data stays private and can be self-hosted.',
    whatsNew:'New exercise search with muscle group filters, improved workout timer, and rest period reminders.',
    permissions:['None — local storage only'],
    screenshots:[
      { title:'Workout Log', caption:'Log exercises with sets, reps, and weight', color:'#e17055', mockup:'list', link:'https://wger.de/en/workout/overview' },
      { title:'Routines', caption:'Create and schedule weekly workout plans', color:'#d63031', mockup:'list', link:'https://wger.de/en/routine/overview' },
      { title:'Nutrition', caption:'Track calories, protein, carbs, and fats', color:'#00b894', mockup:'chart', link:'https://wger.de/en/nutrition/api/nutritionplan/' },
      { title:'Progress', caption:'Charts showing strength and body measurements', color:'#0984e3', mockup:'chart', link:'https://wger.de/en/weight/overview/' },
    ] },

  // Developer Tools
  { id: 'stackblitz',   icon:'⚡', name:'StackBlitz',       desc:'Full-stack web IDE running entirely in the browser. Instant dev environments.',     category:'Developer Tools', price:'Free', url:'https://stackblitz.com', score:4,  trust:'green',  installs:'1.2M', rankingScore:94, safetyScore:97, averageRating:4.8, totalReviews:3200, publishedAt:'2024-01-30', developerTrust:96, installVelocity:88, badges:['trending','verified','top_rated'],
    developer:'StackBlitz Inc.', size:'5.2 MB',
    longDesc:'StackBlitz is a full-stack web IDE that runs entirely in your browser using WebContainers technology. Get instant dev environments for React, Vue, Angular, Next.js, and more. Full Node.js runtime, npm support, and VS Code-powered editor with IntelliSense — no cloud VM needed.',
    whatsNew:'Added Svelte 5 and Astro templates, improved TypeScript IntelliSense, and faster cold boot times.',
    permissions:['Service Worker'],
    screenshots:[
      { title:'Code Editor', caption:'VS Code-powered editor with IntelliSense', color:'#1e90ff', mockup:'editor', link:'https://stackblitz.com' },
      { title:'Live Preview', caption:'Instant hot-reload preview as you type', color:'#2d3436', mockup:'editor', link:'https://stackblitz.com' },
      { title:'Terminal', caption:'Full terminal with npm, node, and git', color:'#636e72', mockup:'editor', link:'https://stackblitz.com' },
      { title:'Templates', caption:'Start from React, Vue, Angular, or Next.js', color:'#6c5ce7', mockup:'grid', link:'https://stackblitz.com/?starters=frontend' },
    ] },
  { id: 'codesandbox',  icon:'📦', name:'CodeSandbox',      desc:'Online code editor and prototyping tool. Instant previews and collaboration.',      category:'Developer Tools', price:'Free', url:'https://codesandbox.io', score:5,  trust:'green',  installs:'890k', rankingScore:90, safetyScore:96, averageRating:4.7, totalReviews:2600, publishedAt:'2024-02-15', developerTrust:95, installVelocity:85, badges:['trending','verified','top_rated'],
    developer:'CodeSandbox B.V.', size:'4.8 MB',
    longDesc:'CodeSandbox is an online code editor and cloud development platform. Create sandboxes for rapid prototyping or use DevBoxes for full-featured cloud VMs. Real-time collaboration, instant previews, and one-click deploy to Vercel or Netlify.',
    whatsNew:'New DevBox environments with GPU support, improved collaboration cursor sharing, and faster preview loading.',
    permissions:['Internet access', 'Service Worker'],
    screenshots:[
      { title:'Sandbox Editor', caption:'Write code with real-time preview panel', color:'#2d3436', mockup:'editor', link:'https://codesandbox.io/s' },
      { title:'DevBoxes', caption:'Full Linux VM environments in the cloud', color:'#151515', mockup:'editor', link:'https://codesandbox.io/dashboard' },
      { title:'Collaboration', caption:'Share sandboxes and code together live', color:'#6c5ce7', mockup:'editor', link:'https://codesandbox.io' },
      { title:'Deploy', caption:'One-click deploy to Vercel or Netlify', color:'#0984e3', mockup:'form', link:'https://codesandbox.io' },
    ] },

  // Entertainment
  { id: 'spotify',      icon:'🎵', name:'Spotify',          desc:'Stream millions of songs, podcasts, and audiobooks. Free tier with ads.',           category:'Entertainment',   price:'Free', url:'https://open.spotify.com', score:3,  trust:'green',  installs:'5.2M', rankingScore:98, safetyScore:98, averageRating:4.8, totalReviews:8400, publishedAt:'2024-01-05', developerTrust:99, installVelocity:97, badges:['trending','verified','top_rated'],
    developer:'Spotify AB', size:'6.1 MB',
    longDesc:'Spotify gives you access to millions of songs, podcasts, and audiobooks. Discover new music through personalized playlists like Discover Weekly and Daily Mix. Free tier includes shuffle play with ads; Premium removes ads and enables offline downloads.',
    whatsNew:'Improved DJ AI feature, new audiobook browsing, redesigned Now Playing screen, and Spotify Wrapped updates.',
    permissions:['Internet access', 'Media playback'],
    screenshots:[
      { title:'Home Feed', caption:'Personalized playlists and daily mixes', color:'#1DB954', mockup:'cards', link:'https://open.spotify.com' },
      { title:'Now Playing', caption:'Full-screen player with lyrics and queue', color:'#191414', mockup:'player', link:'https://open.spotify.com' },
      { title:'Search', caption:'Browse by genre, mood, charts, and new releases', color:'#535353', mockup:'grid', link:'https://open.spotify.com/search' },
      { title:'Library', caption:'Your saved songs, albums, and playlists', color:'#282828', mockup:'list', link:'https://open.spotify.com/collection' },
    ] },
  { id: 'youtube-music',icon:'🎶', name:'YouTube Music',    desc:'Official music streaming from YouTube. Free with ads, background play.',            category:'Entertainment',   price:'Free', url:'https://music.youtube.com', score:4,  trust:'green',  installs:'4.1M', rankingScore:96, safetyScore:97, averageRating:4.6, totalReviews:6200, publishedAt:'2024-01-10', developerTrust:99, installVelocity:95, badges:['trending','verified','top_rated'],
    developer:'Google LLC', size:'5.4 MB',
    longDesc:'YouTube Music is Google\'s official music streaming service with access to official albums, singles, live performances, remixes, and music videos. Personalized recommendations powered by Google AI. Switch between audio and video modes seamlessly.',
    whatsNew:'New mood-based radio stations, improved offline mixtape, redesigned artist pages, and better queue management.',
    permissions:['Internet access', 'Media playback'],
    screenshots:[
      { title:'Home', caption:'Trending music and personalized recommendations', color:'#FF0000', mockup:'cards', link:'https://music.youtube.com' },
      { title:'Player', caption:'Video and audio modes with background play', color:'#282828', mockup:'player', link:'https://music.youtube.com' },
      { title:'Explore', caption:'Charts, new releases, and moods & genres', color:'#212121', mockup:'grid', link:'https://music.youtube.com/explore' },
      { title:'Library', caption:'Downloads, playlists, and subscriptions', color:'#181818', mockup:'list', link:'https://music.youtube.com/library' },
    ] },

  // Education
  { id: 'duolingo',     icon:'🦉', name:'Duolingo',         desc:'Learn 40+ languages for free with bite-sized lessons and gamification.',            category:'Education',       price:'Free', url:'https://www.duolingo.com', score:3,  trust:'green',  installs:'3.8M', rankingScore:97, safetyScore:98, averageRating:4.7, totalReviews:7100, publishedAt:'2024-01-18', developerTrust:98, installVelocity:94, badges:['trending','verified','top_rated'],
    developer:'Duolingo Inc.', size:'4.5 MB',
    longDesc:'Duolingo makes learning languages fun with bite-sized lessons, gamification, and streak tracking. Learn 40+ languages including Spanish, French, Japanese, and Korean. Interactive exercises include listening, speaking, translation, and matching. Compete on leaderboards and earn XP.',
    whatsNew:'New math and music courses, improved speech recognition, redesigned lesson interface, and Duolingo Max with AI roleplay.',
    permissions:['Internet access', 'Microphone (optional, for speaking exercises)'],
    screenshots:[
      { title:'Lesson Tree', caption:'Skill tree with progressive difficulty levels', color:'#58CC02', mockup:'grid', link:'https://www.duolingo.com/learn' },
      { title:'Practice', caption:'Interactive exercises — match, translate, speak', color:'#89E219', mockup:'form', link:'https://www.duolingo.com/practice' },
      { title:'Leaderboards', caption:'Compete with friends and earn XP streaks', color:'#FF9600', mockup:'feed', link:'https://www.duolingo.com/leaderboard' },
      { title:'Stories', caption:'Read and listen to interactive short stories', color:'#CE82FF', mockup:'cards', link:'https://www.duolingo.com/stories' },
    ] },
  { id: 'khan-academy', icon:'🎓', name:'Khan Academy',     desc:'Free world-class education. Math, science, computing, and more.',                   category:'Education',       price:'Free', url:'https://www.khanacademy.org', score:2,  trust:'green',  installs:'2.6M', rankingScore:95, safetyScore:99, averageRating:4.9, totalReviews:5500, publishedAt:'2024-02-01', developerTrust:99, installVelocity:88, badges:['verified','top_rated'],
    developer:'Khan Academy', size:'3.9 MB',
    longDesc:'Khan Academy offers free world-class education in math, science, computing, economics, and more. Expert-led video lessons with interactive transcripts, step-by-step practice problems with hints, and a mastery system that tracks your learning progress. Used by millions of students and teachers worldwide.',
    whatsNew:'AI tutor Khanmigo integration, new AP course prep materials, improved progress dashboard, and offline video support.',
    permissions:['Internet access'],
    screenshots:[
      { title:'Course Library', caption:'Math, science, computing, economics & more', color:'#1865f2', mockup:'grid', link:'https://www.khanacademy.org/subjects' },
      { title:'Video Lessons', caption:'Expert-led videos with interactive transcripts', color:'#14bf96', mockup:'player', link:'https://www.khanacademy.org' },
      { title:'Practice', caption:'Step-by-step problem solving with hints', color:'#ff914d', mockup:'form', link:'https://www.khanacademy.org/math' },
      { title:'Progress', caption:'Mastery system tracking your learning journey', color:'#9b59b6', mockup:'chart', link:'https://www.khanacademy.org/profile' },
    ] },

  // Games
  { id: 'wordle',       icon:'🟩', name:'Wordle',           desc:'Guess the 5-letter word in 6 tries. Daily puzzle, share your results.',             category:'Games',           price:'Free', url:'https://www.nytimes.com/games/wordle', score:2,  trust:'green',  installs:'4.5M', rankingScore:97, safetyScore:99, averageRating:4.9, totalReviews:9200, publishedAt:'2024-01-02', developerTrust:99, installVelocity:92, badges:['trending','verified','top_rated'],
    developer:'The New York Times', size:'0.8 MB',
    longDesc:'Wordle is the viral daily word puzzle from The New York Times. Guess the hidden 5-letter word in 6 tries. Each guess reveals which letters are correct (green), misplaced (yellow), or absent (gray). One puzzle per day — share your spoiler-free results grid with friends.',
    whatsNew:'Added hard mode, new accessibility features, improved statistics sharing, and dark/high-contrast themes.',
    permissions:['None — fully offline'],
    screenshots:[
      { title:'Game Board', caption:'6 rows of 5 tiles — guess the daily word', color:'#538d4e', mockup:'game', link:'https://www.nytimes.com/games/wordle' },
      { title:'Keyboard', caption:'Color-coded keyboard shows used letters', color:'#3a3a3c', mockup:'game', link:'https://www.nytimes.com/games/wordle' },
      { title:'Statistics', caption:'Track your streak and guess distribution', color:'#818384', mockup:'chart', link:'https://www.nytimes.com/games/wordle' },
      { title:'Share Results', caption:'Share your spoiler-free result grid', color:'#b59f3b', mockup:'grid', link:'https://www.nytimes.com/games/wordle' },
    ] },
  { id: '2048',         icon:'🔢', name:'2048',             desc:'Slide numbered tiles on a grid to combine them and reach 2048. Addictive classic.', category:'Games',           price:'Free', url:'https://play2048.co', score:2,  trust:'green',  installs:'1.9M', rankingScore:90, safetyScore:99, averageRating:4.8, totalReviews:4800, publishedAt:'2024-03-05', developerTrust:95, installVelocity:78, badges:['verified','top_rated'],
    developer:'Gabriele Cirulli', size:'0.3 MB',
    longDesc:'2048 is the classic sliding tile puzzle. Swipe to move tiles on a 4x4 grid — when two tiles with the same number touch, they merge into one. Reach the 2048 tile to win, then keep going for higher scores. Simple to learn, incredibly addictive.',
    whatsNew:'Added undo button, new color themes, improved swipe gestures, and persistent high score tracking.',
    permissions:['None — fully offline'],
    screenshots:[
      { title:'Game Grid', caption:'4x4 grid — swipe to merge matching tiles', color:'#edc22e', mockup:'game', link:'https://play2048.co' },
      { title:'High Scores', caption:'Track your best tile and high score', color:'#f2b179', mockup:'chart', link:'https://play2048.co' },
      { title:'Gameplay', caption:'Strategize to reach 2048 and beyond', color:'#f67c5f', mockup:'game', link:'https://play2048.co' },
      { title:'Game Over', caption:'Final score with option to try again', color:'#edc53f', mockup:'gauge', link:'https://play2048.co' },
    ] },

  // Security
  { id: 'bitwarden',    icon:'🔐', name:'Bitwarden',        desc:'Open source password manager. End-to-end encrypted, free for personal use.',        category:'Security',        price:'Free', url:'https://vault.bitwarden.com', score:3,  trust:'green',  installs:'1.5M', rankingScore:95, safetyScore:99, averageRating:4.8, totalReviews:4100, publishedAt:'2024-01-22', developerTrust:98, installVelocity:90, badges:['trending','verified','top_rated'],
    developer:'Bitwarden Inc.', size:'3.6 MB',
    longDesc:'Bitwarden is a free, open source password manager with end-to-end encryption. Store unlimited passwords, passkeys, credit cards, and secure notes. Auto-fill credentials on any website. Available on every platform with sync across all your devices. Audited by third-party security firms.',
    whatsNew:'Added passkey support, improved auto-fill accuracy, new security report dashboard, and emergency access feature.',
    permissions:['Internet access', 'Clipboard'],
    screenshots:[
      { title:'Vault', caption:'All your passwords organized in one vault', color:'#175DDC', mockup:'list', link:'https://vault.bitwarden.com/#/vault' },
      { title:'Password Generator', caption:'Create strong unique passwords instantly', color:'#1a3d7c', mockup:'form', link:'https://vault.bitwarden.com/#/generator' },
      { title:'Auto-Fill', caption:'One-click login on any website or app', color:'#339af0', mockup:'form', link:'https://vault.bitwarden.com' },
      { title:'Security Report', caption:'Check for weak, reused, or breached passwords', color:'#0d47a1', mockup:'chart', link:'https://vault.bitwarden.com/#/reports' },
    ] },
  { id: 'protonpass',   icon:'🛡️', name:'Proton Pass',      desc:'End-to-end encrypted password manager from the makers of ProtonMail.',              category:'Security',        price:'Free', url:'https://pass.proton.me', score:4,  trust:'green',  installs:'620k', rankingScore:86, safetyScore:98, averageRating:4.7, totalReviews:1800, publishedAt:'2024-04-15', developerTrust:96, installVelocity:82, badges:['trending','verified'],
    developer:'Proton AG', size:'2.9 MB',
    longDesc:'Proton Pass is an end-to-end encrypted password manager from the team behind ProtonMail. Store logins, generate email aliases to protect your inbox, save encrypted notes, and use passkeys for passwordless login. Swiss privacy laws protect your data.',
    whatsNew:'New email alias management, passkey login support, improved vault sharing, and integrated 2FA code generator.',
    permissions:['Internet access', 'Clipboard'],
    screenshots:[
      { title:'Logins', caption:'Store and organize all your login credentials', color:'#6d4aff', mockup:'list', link:'https://pass.proton.me' },
      { title:'Aliases', caption:'Generate email aliases to protect your inbox', color:'#8b5cf6', mockup:'list', link:'https://pass.proton.me' },
      { title:'Secure Notes', caption:'Encrypted notes for sensitive information', color:'#7c3aed', mockup:'form', link:'https://pass.proton.me' },
      { title:'Passkeys', caption:'Passwordless login with passkey support', color:'#a78bfa', mockup:'form', link:'https://pass.proton.me' },
    ] },

  // Business
  { id: 'trello',       icon:'📋', name:'Trello',           desc:'Visual project management with boards, lists, and cards. Free for small teams.',    category:'Business',        price:'Free', url:'https://trello.com', score:4,  trust:'green',  installs:'2.8M', rankingScore:94, safetyScore:97, averageRating:4.7, totalReviews:5600, publishedAt:'2024-01-25', developerTrust:97, installVelocity:86, badges:['trending','verified','top_rated'],
    developer:'Atlassian', size:'4.3 MB',
    longDesc:'Trello is a visual collaboration tool used by millions for project management. Organize anything with boards, lists, and cards. Drag and drop cards across lists, add checklists, due dates, attachments, and labels. Power-Ups extend functionality with calendars, automation, and integrations.',
    whatsNew:'New timeline view, improved card templates, better mobile drag-and-drop, and enhanced Butler automation.',
    permissions:['Internet access', 'Notifications'],
    screenshots:[
      { title:'Board View', caption:'Drag-and-drop cards across lists', color:'#0079BF', mockup:'board', link:'https://trello.com' },
      { title:'Card Detail', caption:'Checklists, due dates, attachments, and labels', color:'#00C2E0', mockup:'form', link:'https://trello.com' },
      { title:'Calendar', caption:'See all due dates in a calendar view', color:'#51E898', mockup:'grid', link:'https://trello.com' },
      { title:'Team Boards', caption:'Collaborate with your team in real time', color:'#FF9F1A', mockup:'board', link:'https://trello.com' },
    ] },
  { id: 'slack',        icon:'💬', name:'Slack',            desc:'Team messaging and collaboration hub. Channels, threads, and integrations.',        category:'Business',        price:'Free', url:'https://app.slack.com', score:5,  trust:'green',  installs:'3.2M', rankingScore:96, safetyScore:97, averageRating:4.6, totalReviews:6800, publishedAt:'2024-01-08', developerTrust:98, installVelocity:92, badges:['trending','verified','top_rated'],
    developer:'Salesforce (Slack)', size:'5.7 MB',
    longDesc:'Slack is the collaboration hub that brings teams together. Organize conversations into channels by project, team, or topic. Use threads for focused discussions, huddles for quick audio calls, and connect 2,400+ integrations. Search across all messages and files instantly.',
    whatsNew:'New Slack AI for message summaries, improved huddle video quality, canvas documents, and workflow builder updates.',
    permissions:['Internet access', 'Notifications', 'Microphone (optional)'],
    screenshots:[
      { title:'Channels', caption:'Organized conversations by team and topic', color:'#4A154B', mockup:'chat', link:'https://app.slack.com' },
      { title:'Threads', caption:'Keep discussions focused with threaded replies', color:'#611f69', mockup:'chat', link:'https://app.slack.com' },
      { title:'Search', caption:'Find any message, file, or person instantly', color:'#36C5F0', mockup:'form', link:'https://app.slack.com' },
      { title:'Huddles', caption:'Quick audio calls without leaving Slack', color:'#2EB67D', mockup:'chat', link:'https://app.slack.com' },
    ] },

  // Food & Cooking
  { id: 'mealime',      icon:'🥗', name:'Mealime',          desc:'Meal planning made simple. Personalized recipes and auto grocery lists.',           category:'Food & Cooking',  price:'Free', url:'https://www.mealime.com', score:5,  trust:'green',  installs:'380k', rankingScore:78, safetyScore:94, averageRating:4.6, totalReviews:1200, publishedAt:'2024-06-01', developerTrust:85, installVelocity:65, badges:['verified','top_rated'],
    developer:'Mealime', size:'2.6 MB',
    longDesc:'Mealime simplifies meal planning with personalized recipes based on your dietary preferences. Generate weekly meal plans, get auto-generated grocery lists, and follow step-by-step cooking instructions. Supports vegan, keto, gluten-free, and other dietary needs.',
    whatsNew:'Added 200+ new recipes, improved grocery list organization by store aisle, and better serving size adjustments.',
    permissions:['Internet access'],
    screenshots:[
      { title:'Meal Plan', caption:'Drag recipes into your weekly meal plan', color:'#27ae60', mockup:'list', link:'https://www.mealime.com' },
      { title:'Recipes', caption:'Step-by-step cooking instructions with photos', color:'#2ecc71', mockup:'cards', link:'https://www.mealime.com/recipes' },
      { title:'Grocery List', caption:'Auto-generated shopping list from your plan', color:'#f39c12', mockup:'list', link:'https://www.mealime.com' },
      { title:'Preferences', caption:'Set dietary needs — vegan, keto, gluten-free', color:'#e74c3c', mockup:'form', link:'https://www.mealime.com' },
    ] },
  { id: 'cookpad',      icon:'👨‍🍳', name:'Cookpad',          desc:'Community-driven recipe sharing. Millions of home-cooked recipes from real cooks.', category:'Food & Cooking',  price:'Free', url:'https://cookpad.com', score:6,  trust:'green',  installs:'520k', rankingScore:80, safetyScore:93, averageRating:4.5, totalReviews:1500, publishedAt:'2024-05-18', developerTrust:86, installVelocity:68, badges:['verified'],
    developer:'Cookpad Inc.', size:'3.1 MB',
    longDesc:'Cookpad is the world\'s largest community-driven recipe platform with millions of recipes from home cooks. Browse by ingredient, cuisine, or dietary need. Step-by-step cooking mode with timers and voice control. Save favorites to personal cookbooks and share your own creations.',
    whatsNew:'New cooking mode with hands-free voice commands, improved recipe search, and video recipe support.',
    permissions:['Internet access', 'Microphone (optional, for voice control)'],
    screenshots:[
      { title:'Recipe Feed', caption:'Browse recipes shared by home cooks worldwide', color:'#f57f17', mockup:'feed', link:'https://cookpad.com/search' },
      { title:'Cooking Mode', caption:'Step-by-step with timers and voice control', color:'#e65100', mockup:'list', link:'https://cookpad.com' },
      { title:'My Cookbooks', caption:'Save and organize your favorite recipes', color:'#ff8f00', mockup:'grid', link:'https://cookpad.com/collections' },
      { title:'Share Recipe', caption:'Upload your own recipes with photos', color:'#ef6c00', mockup:'form', link:'https://cookpad.com/recipe/new' },
    ] },

  // Social
  { id: 'mastodon',     icon:'🐘', name:'Mastodon',         desc:'Decentralized social network. No ads, no algorithms, no corporate surveillance.',   category:'Social',          price:'Free', url:'https://mastodon.social', score:5,  trust:'green',  installs:'890k', rankingScore:84, safetyScore:96, averageRating:4.5, totalReviews:2400, publishedAt:'2024-03-12', developerTrust:92, installVelocity:74, badges:['verified','top_rated'],
    developer:'Mastodon gGmbH', size:'2.8 MB',
    longDesc:'Mastodon is a decentralized social network where you own your data. No ads, no algorithms, no corporate surveillance. Join any server or host your own. Follow people across the fediverse, post with up to 500 characters, and enjoy a chronological timeline.',
    whatsNew:'Improved onboarding flow, new quote posts feature, better content moderation tools, and faster federation.',
    permissions:['Internet access', 'Notifications'],
    screenshots:[
      { title:'Home Timeline', caption:'Posts from people you follow, chronologically', color:'#6364FF', mockup:'feed', link:'https://mastodon.social/home' },
      { title:'Explore', caption:'Trending posts, hashtags, and news', color:'#563ACC', mockup:'feed', link:'https://mastodon.social/explore' },
      { title:'Notifications', caption:'Mentions, boosts, and new followers', color:'#858AFA', mockup:'list', link:'https://mastodon.social/notifications' },
      { title:'Profile', caption:'Your posts, media, and followers list', color:'#2F0C7A', mockup:'cards', link:'https://mastodon.social/profile' },
    ] },

  // Shopping
  { id: 'honey',        icon:'🍯', name:'Honey by PayPal',  desc:'Automatically find and apply coupon codes at checkout. Save money effortlessly.',   category:'Shopping',        price:'Free', url:'https://www.joinhoney.com', score:7,  trust:'green',  installs:'1.1M', rankingScore:86, safetyScore:92, averageRating:4.5, totalReviews:3200, publishedAt:'2024-04-20', developerTrust:93, installVelocity:78, badges:['trending','verified'],
    developer:'PayPal Inc.', size:'2.2 MB',
    longDesc:'Honey by PayPal automatically finds and applies the best coupon codes at checkout on 30,000+ online stores. Track prices with Droplist to get notified when items drop in price. Earn Honey Gold rewards on qualifying purchases and redeem for gift cards.',
    whatsNew:'Expanded store coverage, improved coupon success rate, new price history charts, and faster checkout integration.',
    permissions:['Internet access'],
    screenshots:[
      { title:'Apply Coupons', caption:'Automatically tests all available codes', color:'#FF6801', mockup:'list', link:'https://www.joinhoney.com' },
      { title:'Savings', caption:'Track total savings across all your purchases', color:'#f59e0b', mockup:'chart', link:'https://www.joinhoney.com' },
      { title:'Droplist', caption:'Track price drops on items you want', color:'#ec4899', mockup:'feed', link:'https://www.joinhoney.com/droplist' },
      { title:'Rewards', caption:'Earn Honey Gold for cash back on purchases', color:'#fbbf24', mockup:'grid', link:'https://www.joinhoney.com' },
    ] },

  // Travel
  { id: 'google-maps',  icon:'🗺️', name:'Google Maps',      desc:'Navigate the world with real-time traffic, transit, and offline maps.',              category:'Travel',          price:'Free', url:'https://www.google.com/maps', score:3,  trust:'green',  installs:'6.1M', rankingScore:99, safetyScore:98, averageRating:4.8, totalReviews:12000,publishedAt:'2024-01-01', developerTrust:99, installVelocity:98, badges:['trending','verified','top_rated'],
    developer:'Google LLC', size:'7.2 MB',
    longDesc:'Google Maps helps you navigate the world with real-time GPS navigation, traffic updates, and transit directions. Explore satellite imagery, Street View, and indoor maps. Find restaurants, shops, and attractions nearby with reviews, photos, and business hours. Download areas for offline navigation.',
    whatsNew:'Immersive View for routes, improved EV charging station info, enhanced cycling directions, and real-time transit crowd levels.',
    permissions:['Location (optional)', 'Internet access'],
    screenshots:[
      { title:'Map View', caption:'Satellite, terrain, and street-level imagery', color:'#4285F4', mockup:'map', link:'https://www.google.com/maps/@0,0,3z' },
      { title:'Navigation', caption:'Turn-by-turn driving, walking, and cycling', color:'#34A853', mockup:'map', link:'https://www.google.com/maps/dir/' },
      { title:'Transit', caption:'Real-time bus, train, and subway schedules', color:'#FBBC04', mockup:'list', link:'https://www.google.com/maps/dir/?travelmode=transit' },
      { title:'Explore', caption:'Find restaurants, shops, and attractions nearby', color:'#EA4335', mockup:'grid', link:'https://www.google.com/maps/search/restaurants+nearby' },
    ] },

  // Music
  { id: 'soundtrap',    icon:'🎹', name:'Soundtrap',        desc:'Online music studio by Spotify. Record, mix, and collaborate on music for free.',   category:'Music',           price:'Free', url:'https://www.soundtrap.com', score:5,  trust:'green',  installs:'420k', rankingScore:79, safetyScore:95, averageRating:4.5, totalReviews:1100, publishedAt:'2024-05-25', developerTrust:94, installVelocity:62, badges:['verified'],
    developer:'Spotify (Soundtrap AB)', size:'4.9 MB',
    longDesc:'Soundtrap is an online music studio by Spotify for recording, mixing, and collaborating on music. Multi-track editor with virtual instruments, loops, and effects. Invite collaborators for real-time remote sessions. No software install needed — works entirely in your browser.',
    whatsNew:'New AI beat maker, expanded loop library, improved MIDI keyboard support, and podcast editing tools.',
    permissions:['Internet access', 'Microphone'],
    screenshots:[
      { title:'Studio', caption:'Multi-track editor with loops and instruments', color:'#1DB954', mockup:'editor', link:'https://www.soundtrap.com/studio' },
      { title:'Instruments', caption:'Synths, drums, and virtual instruments', color:'#191414', mockup:'grid', link:'https://www.soundtrap.com' },
      { title:'Loops Library', caption:'Thousands of royalty-free loops and beats', color:'#535353', mockup:'grid', link:'https://www.soundtrap.com' },
      { title:'Collaborate', caption:'Invite friends to produce together in real time', color:'#282828', mockup:'chat', link:'https://www.soundtrap.com' },
    ] },

  // Photography
  { id: 'photopea',     icon:'📸', name:'Photopea',         desc:'Free online photo editor. Supports PSD, XCF, Sketch, XD, and CDR formats.',        category:'Photography',     price:'Free', url:'https://www.photopea.com', score:4,  trust:'green',  installs:'1.8M', rankingScore:92, safetyScore:96, averageRating:4.7, totalReviews:3900, publishedAt:'2024-02-10', developerTrust:93, installVelocity:86, badges:['trending','verified','top_rated'],
    developer:'Ivan Kutskir', size:'3.4 MB',
    longDesc:'Photopea is a free, browser-based image editor with a Photoshop-like interface. Open and edit PSD, XCF, Sketch, XD, and CDR files directly. Full layer support with blending modes, masks, and smart objects. Apply filters, adjustments, and effects. Export to PSD, PNG, JPG, SVG, GIF, and PDF.',
    whatsNew:'Added AI-powered background removal, new content-aware fill, improved pen tool, and faster PSD file loading.',
    permissions:['None — fully offline capable'],
    screenshots:[
      { title:'Editor', caption:'Photoshop-like interface with layers and tools', color:'#18A0FB', mockup:'editor', link:'https://www.photopea.com' },
      { title:'Layers Panel', caption:'Full layer support with blending modes', color:'#2c3e50', mockup:'list', link:'https://www.photopea.com' },
      { title:'Filters', caption:'Blur, sharpen, color adjustments, and effects', color:'#8e44ad', mockup:'grid', link:'https://www.photopea.com' },
      { title:'Export', caption:'Save as PSD, PNG, JPG, SVG, GIF, and PDF', color:'#16a085', mockup:'form', link:'https://www.photopea.com' },
    ] },
  { id: 'squoosh',      icon:'🖼️', name:'Squoosh',          desc:'Image compression app by Google. Resize and optimize images right in the browser.', category:'Photography',     price:'Free', url:'https://squoosh.app', score:2,  trust:'green',  installs:'680k', rankingScore:85, safetyScore:99, averageRating:4.8, totalReviews:2100, publishedAt:'2024-03-20', developerTrust:99, installVelocity:72, badges:['verified','top_rated'],
    developer:'Google Chrome Labs', size:'1.2 MB',
    longDesc:'Squoosh is a lightweight image compression tool built by Google Chrome Labs. Compare original and compressed versions side-by-side with an interactive slider. Supports WebP, AVIF, JPEG, and PNG output formats. Resize images and see file size savings instantly. Works entirely offline.',
    whatsNew:'Added JPEG XL support, batch compression mode, improved AVIF quality, and faster encoding performance.',
    permissions:['None — fully offline'],
    screenshots:[
      { title:'Compare', caption:'Side-by-side before/after quality comparison', color:'#4285F4', mockup:'editor', link:'https://squoosh.app' },
      { title:'Compress', caption:'Choose WebP, AVIF, JPEG, or PNG output', color:'#34A853', mockup:'form', link:'https://squoosh.app' },
      { title:'Resize', caption:'Resize with fit, fill, or exact dimensions', color:'#FBBC04', mockup:'form', link:'https://squoosh.app' },
      { title:'Results', caption:'See file size reduction percentage instantly', color:'#EA4335', mockup:'gauge', link:'https://squoosh.app' },
    ] },

  // Weather
  { id: 'windy',        icon:'🌤️', name:'Windy',            desc:'Detailed weather forecasts with interactive radar maps. Used by pilots and sailors.',category:'Weather',         price:'Free', url:'https://www.windy.com', score:4,  trust:'green',  installs:'1.4M', rankingScore:91, safetyScore:96, averageRating:4.7, totalReviews:3600, publishedAt:'2024-02-28', developerTrust:94, installVelocity:80, badges:['trending','verified','top_rated'],
    developer:'Windyty SE', size:'4.6 MB',
    longDesc:'Windy is a powerful weather app with interactive radar maps used by pilots, sailors, and outdoor enthusiasts. View animated wind, rain, temperature, and cloud layers on a global map. Get detailed hourly and 10-day forecasts from multiple weather models. Set severe weather alerts for your locations.',
    whatsNew:'New lightning detection layer, improved hurricane tracking, better webcam integration, and point forecast accuracy.',
    permissions:['Location (optional)', 'Internet access'],
    screenshots:[
      { title:'Wind Map', caption:'Animated wind patterns across the globe', color:'#1565c0', mockup:'map', link:'https://www.windy.com/?wind' },
      { title:'Radar', caption:'Rain, snow, temperature, and cloud layers', color:'#0d47a1', mockup:'map', link:'https://www.windy.com/?rain' },
      { title:'Forecast', caption:'Hourly and 10-day detailed forecasts', color:'#42a5f5', mockup:'chart', link:'https://www.windy.com' },
      { title:'Alerts', caption:'Severe weather warnings and notifications', color:'#ef5350', mockup:'list', link:'https://www.windy.com/alerts' },
    ] },

  // News
  { id: 'hackernews',   icon:'📰', name:'Hacker News',      desc:'Tech news and discussion from Y Combinator. Top stories, comments, and jobs.',     category:'News',            price:'Free', url:'https://news.ycombinator.com', score:3,  trust:'green',  installs:'720k', rankingScore:83, safetyScore:97, averageRating:4.6, totalReviews:1900, publishedAt:'2024-04-02', developerTrust:96, installVelocity:70, badges:['verified','top_rated'],
    developer:'Y Combinator', size:'0.5 MB',
    longDesc:'Hacker News is the tech community\'s front page, run by Y Combinator. Read top stories about startups, programming, science, and technology. Participate in thoughtful discussions with expert developers and founders. Browse Ask HN threads and YC company job postings.',
    whatsNew:'Improved comment threading, faster page loads, new dark mode, and better mobile reading experience.',
    permissions:['Internet access'],
    screenshots:[
      { title:'Top Stories', caption:'Ranked tech news and startup discussions', color:'#FF6600', mockup:'feed', link:'https://news.ycombinator.com' },
      { title:'Comments', caption:'Threaded discussions with expert insights', color:'#f5f5dc', mockup:'feed', link:'https://news.ycombinator.com/newcomments' },
      { title:'Ask HN', caption:'Community questions and advice threads', color:'#ff851b', mockup:'feed', link:'https://news.ycombinator.com/ask' },
      { title:'Jobs', caption:'Startup job postings from YC companies', color:'#e67e22', mockup:'list', link:'https://news.ycombinator.com/jobs' },
    ] },

  // Sports
  { id: 'strava',       icon:'🏋️', name:'Strava',           desc:'Track running, cycling, and workouts. Compete with friends and join challenges.',   category:'Sports',          price:'Free', url:'https://www.strava.com', score:5,  trust:'green',  installs:'2.4M', rankingScore:94, safetyScore:96, averageRating:4.7, totalReviews:5200, publishedAt:'2024-01-28', developerTrust:96, installVelocity:89, badges:['trending','verified','top_rated'],
    developer:'Strava Inc.', size:'5.1 MB',
    longDesc:'Strava is the social network for athletes. Track your runs, rides, hikes, and workouts with GPS. Compete on popular segments and earn crowns. Join monthly challenges, follow friends, and share your achievements. Detailed analytics for pace, heart rate, elevation, and power.',
    whatsNew:'New route builder with terrain data, improved segment matching, dark mode support, and training log improvements.',
    permissions:['Location', 'Internet access'],
    screenshots:[
      { title:'Activity Feed', caption:'See runs, rides, and workouts from friends', color:'#FC4C02', mockup:'feed', link:'https://www.strava.com/dashboard' },
      { title:'GPS Tracking', caption:'Map your route with pace and elevation', color:'#2d3436', mockup:'map', link:'https://www.strava.com/record' },
      { title:'Segments', caption:'Compete on popular routes and earn crowns', color:'#e17055', mockup:'chart', link:'https://www.strava.com/segments/explore' },
      { title:'Challenges', caption:'Monthly challenges and club competitions', color:'#ff7675', mockup:'list', link:'https://www.strava.com/challenges' },
    ] },

  // Utilities
  { id: 'speedtest',    icon:'🔧', name:'Speedtest by Ookla',desc:'Test your internet speed — download, upload, ping, and jitter.',                  category:'Utilities',       price:'Free', url:'https://www.speedtest.net', score:3,  trust:'green',  installs:'3.1M', rankingScore:95, safetyScore:97, averageRating:4.7, totalReviews:6400, publishedAt:'2024-01-12', developerTrust:97, installVelocity:90, badges:['trending','verified','top_rated'],
    developer:'Ookla LLC', size:'2.0 MB',
    longDesc:'Speedtest by Ookla is the world\'s most popular internet speed test. Measure your download speed, upload speed, ping, and jitter with a single tap. View detailed results, track speed history over time, and see ISP and server information. Test on thousands of servers worldwide.',
    whatsNew:'New video speed test, improved server selection algorithm, result comparison graphs, and VPN detection indicator.',
    permissions:['Internet access'],
    screenshots:[
      { title:'Speed Test', caption:'One-tap download and upload speed test', color:'#141526', mockup:'gauge', link:'https://www.speedtest.net' },
      { title:'Results', caption:'Download, upload, ping, and jitter metrics', color:'#1c1d3b', mockup:'chart', link:'https://www.speedtest.net/result' },
      { title:'History', caption:'Track speed over time with detailed logs', color:'#6c5ce7', mockup:'chart', link:'https://www.speedtest.net' },
      { title:'Network Info', caption:'See ISP, server, and connection details', color:'#a29bfe', mockup:'list', link:'https://www.speedtest.net' },
    ] },
  { id: 'clipdrop',     icon:'✂️', name:'Clipdrop',         desc:'AI-powered tool to remove backgrounds, upscale images, and clean up photos.',       category:'Utilities',       price:'Free', url:'https://clipdrop.co', score:5,  trust:'green',  installs:'580k', rankingScore:82, safetyScore:94, averageRating:4.6, totalReviews:1600, publishedAt:'2024-05-05', developerTrust:90, installVelocity:75, badges:['verified','top_rated'],
    developer:'Stability AI', size:'2.7 MB',
    longDesc:'Clipdrop is an AI-powered creative toolkit. Remove backgrounds instantly, upscale images to 4x resolution, clean up photos by removing unwanted objects, and relight scenes with AI. Powered by Stability AI\'s machine learning models. No design skills required.',
    whatsNew:'New text removal tool, improved background removal accuracy, batch processing mode, and API access for developers.',
    permissions:['Internet access'],
    screenshots:[
      { title:'Remove BG', caption:'AI background removal in one click', color:'#7c3aed', mockup:'editor', link:'https://clipdrop.co/remove-background' },
      { title:'Upscale', caption:'Enhance image resolution with AI upscaling', color:'#8b5cf6', mockup:'editor', link:'https://clipdrop.co/image-upscaler' },
      { title:'Cleanup', caption:'Remove objects and blemishes from photos', color:'#a78bfa', mockup:'editor', link:'https://clipdrop.co/cleanup' },
      { title:'Relight', caption:'AI relighting to change photo lighting', color:'#c4b5fd', mockup:'editor', link:'https://clipdrop.co/relight' },
    ] },

  // Communication
  { id: 'telegram',     icon:'📧', name:'Telegram',         desc:'Fast, secure messaging with cloud sync. Supports groups, channels, and bots.',      category:'Communication',   price:'Free', url:'https://web.telegram.org', score:4,  trust:'green',  installs:'4.8M', rankingScore:98, safetyScore:96, averageRating:4.7, totalReviews:9800, publishedAt:'2024-01-03', developerTrust:97, installVelocity:96, badges:['trending','verified','top_rated'],
    developer:'Telegram FZ-LLC', size:'4.2 MB',
    longDesc:'Telegram is a fast, secure messaging app with cloud sync across all your devices. Send messages, photos, videos, and files up to 2GB each. Create groups with up to 200,000 members, subscribe to public channels, and build custom bots. End-to-end encrypted secret chats available.',
    whatsNew:'New stories feature, improved voice chat quality, custom emoji packs, and enhanced bot mini-app platform.',
    permissions:['Internet access', 'Notifications', 'Microphone (optional)'],
    screenshots:[
      { title:'Chats', caption:'All conversations with cloud sync across devices', color:'#0088cc', mockup:'chat', link:'https://web.telegram.org' },
      { title:'Channels', caption:'Subscribe to news, updates, and communities', color:'#179cde', mockup:'feed', link:'https://web.telegram.org' },
      { title:'Groups', caption:'Groups up to 200,000 members with admin tools', color:'#40b3e0', mockup:'chat', link:'https://web.telegram.org' },
      { title:'Stickers', caption:'Animated stickers, GIFs, and custom emoji', color:'#5cc3ed', mockup:'grid', link:'https://web.telegram.org' },
    ] },

  // Lifestyle
  { id: 'pinterest',    icon:'📌', name:'Pinterest',        desc:'Discover recipes, home ideas, style inspiration, and more. Save and organize pins.', category:'Lifestyle',       price:'Free', url:'https://www.pinterest.com', score:5,  trust:'green',  installs:'2.9M', rankingScore:95, safetyScore:96, averageRating:4.6, totalReviews:6100, publishedAt:'2024-01-15', developerTrust:97, installVelocity:91, badges:['trending','verified','top_rated'],
    developer:'Pinterest Inc.', size:'5.3 MB',
    longDesc:'Pinterest is a visual discovery platform for finding inspiration. Browse billions of pins for recipes, home decor, fashion, DIY projects, and more. Save ideas to themed boards, use visual search with your camera, and shop products directly from pins you love.',
    whatsNew:'New AI-powered collage feature, improved visual search accuracy, shopping integration updates, and creator analytics.',
    permissions:['Internet access', 'Camera (optional, for visual search)'],
    screenshots:[
      { title:'Home Feed', caption:'Personalized pins based on your interests', color:'#E60023', mockup:'grid', link:'https://www.pinterest.com' },
      { title:'Search', caption:'Visual search with camera lens and filters', color:'#c92a2a', mockup:'grid', link:'https://www.pinterest.com/search' },
      { title:'Boards', caption:'Save and organize pins into themed boards', color:'#bd081c', mockup:'grid', link:'https://www.pinterest.com' },
      { title:'Shopping', caption:'Shop products directly from pins you love', color:'#ad081c', mockup:'cards', link:'https://www.pinterest.com/shopping' },
    ] },
]

export const CATEGORIES = ['All', 'Productivity', 'Finance', 'Health', 'Developer Tools', 'Entertainment', 'Education', 'Games', 'Security', 'Business', 'Food & Cooking', 'Social', 'Shopping', 'Travel', 'Music', 'Photography', 'Weather', 'News', 'Sports', 'Utilities', 'Communication', 'Lifestyle']

export const SCAN_STEPS = [
  { pct:8,  label:'Initializing sandbox',       cls:'info', text:'[init] Pulling node:20-alpine...' },
  { pct:18, label:'Installing dependencies',    cls:'info', text:'[build] npm ci — 47 packages' },
  { pct:30, label:'Building PWA bundle',        cls:'ok',   text:'[build] ✓ Built in 34s — 2.1MB' },
  { pct:40, label:'Generating SBOM',            cls:'info', text:'[sbom] 47 packages inventoried' },
  { pct:50, label:'CVE dependency scan',        cls:'warn', text:'[cve] ⚠ lodash@4.17.20 medium CVE' },
  { pct:60, label:'Static artifact analysis',   cls:'ok',   text:'[sast] ✓ No miners or hidden iframes' },
  { pct:70, label:'Secrets detection',          cls:'ok',   text:'[secrets] ✓ No credentials found' },
  { pct:80, label:'Dynamic sandbox run',        cls:'ok',   text:'[dast] ✓ 0 outbound calls detected' },
  { pct:90, label:'Policy compliance',          cls:'ok',   text:'[policy] ✓ Privacy URL + email verified' },
  { pct:97, label:'Reputation check',           cls:'ok',   text:'[rep] ✓ Publisher clean, 0 strikes' },
  { pct:100,label:'Pipeline complete',          cls:'ok',   text:'[done] Risk score: 12/100 → ALLOW ✅' },
]

export const PIPELINE_STAGES = [
  { num:'01', title:'Pre-Build Static Intake',     desc:'File validation, secrets scan, malware signatures', badge:'pass',
    findings:[
      { sev:'pass', msg:'✓ No binary blobs detected' },
      { sev:'pass', msg:'✓ No API keys or private keys in source' },
      { sev:'pass', msg:'✓ No known malware signatures matched' },
    ]},
  { num:'02', title:'Sandboxed Build + SBOM',      desc:'Docker sandbox, SBOM generation, CVE check', badge:'pass',
    findings:[
      { sev:'pass', msg:'✓ Build succeeded in 34s (React 18)' },
      { sev:'pass', msg:'✓ 47 dependencies inventoried, 0 critical CVEs' },
      { sev:'medium', msg:'⚠ lodash@4.17.20 — 1 medium CVE (no RCE path)' },
    ]},
  { num:'03', title:'Post-Build Artifact Analysis', desc:'Hidden iframes, redirect chains, clipboard hijack, crypto-miners', badge:'pass',
    findings:[
      { sev:'pass', msg:'✓ No hidden iframes or drive-by patterns' },
      { sev:'pass', msg:'✓ No crypto-miner bytecode found' },
      { sev:'pass', msg:'✓ Obfuscation score: 0.12 (normal minification)' },
    ]},
  { num:'04', title:'Dynamic Sandbox Analysis',    desc:'Headless browser — network calls, fingerprinting, redirects', badge:'pass',
    findings:[
      { sev:'pass', msg:'✓ 0 outbound network calls during 60s session' },
      { sev:'pass', msg:'✓ No device fingerprinting detected' },
      { sev:'pass', msg:'✓ No unexpected permission prompts' },
    ]},
  { num:'05', title:'Policy & Compliance',         desc:'Privacy policy, ToS, contact, category-specific rules', badge:'pass',
    findings:[
      { sev:'pass', msg:'✓ Privacy policy URL verified and live' },
      { sev:'pass', msg:'✓ Contact email validated' },
      { sev:'pass', msg:'✓ No restricted health/finance claims in copy' },
    ]},
  { num:'06', title:'Reputation & History',        desc:'Publisher age, prior strikes, version history, report rate', badge:'pass',
    findings:[
      { sev:'pass', msg:'✓ Publisher account: 8 months, 0 strikes' },
      { sev:'pass', msg:'✓ 3 prior clean versions on record' },
      { sev:'pass', msg:'✓ User report rate: 0.00%' },
    ]},
]
